### ISSUE TITLE
Purpose of  github_event.json 

### ISSUE THREAD

**Issue by sobolevn** [mijailr/actions_sample#4]
Hi!

I am moving my setup from travis to github actions. And it seem to work fine even without `github_event.json` file.
So, I would like to clarify what it is and why do we need it?

Because this is a sample repo I believe that this is important.

**Comment by mijailr** [comment]
Thanks @sobolevn your're right, there isn't any reason to have that file in this repository.

**Comment by sobolevn** [comment]
Awesome! Thanks! 

There are plenty of other things that can be updated as well.
See: https://github.com/sobolevn/recase/blob/master/.github/workflows/test.yml

**Comment by mijailr** [comment]
> Awesome! Thanks!
> 
> There are plenty of other things that can be updated as well.
> See: https://github.com/sobolevn/recase/blob/master/.github/workflows/test.yml

Sure, feel free to create a pull request
